[project]
name = "ireul"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argcomplete>=3.6.2",
    "openai>=1.78.0",
    "pyyaml>=6.0.2",
]
[project.scripts]
ireul = "ireul.cli:main"
